name: Validate Template
on: push

permissions:
  contents: read

jobs:
  validate:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Validate Sanity Template
        uses: sanity-io/template-validator@6f6003224268499e7361fa848b0c9eed232a2113 # v2
